/* Dynamic, backend-configurable storefront home runtime. */
(function () {
  'use strict';
  const root=document.getElementById('storefront-home-root'); if(!root)return;
  const REQUESTED=[
    {id:'search',type:'search',enabled:true,content:{},settings:{}},
    {id:'videos',type:'videos',enabled:true,content:{title:'ویدیوهای آموزشی',subtitle:'نکات، آموزش و معرفی محصولات'},settings:{limit:8}},
    {id:'best-sellers',type:'best-sellers',enabled:true,content:{title:'پرفروش‌ترین‌ها',subtitle:'انتخاب‌های محبوب مشتریان'},settings:{mode:'auto',limit:8,productIds:[]}},
    {id:'campaign',type:'campaign',enabled:true,content:{title:'تخفیف‌ها',subtitle:'پیشنهادهای ویژه و محدود'},settings:{productIds:[]}},
    {id:'categories',type:'categories',enabled:true,content:{title:'دسته‌بندی محصولات',subtitle:'انتخاب سریع‌تر با دسته‌بندی تصویری'},settings:{limit:8}}
  ];
  const DEFAULT_CONFIG={sections:REQUESTED};
  const DEFAULT_THEME={primaryColor:'#cf4772',accentColor:'#452b45',backgroundColor:'#fffdfc',surfaceColor:'#fff',textColor:'#211b1e',mutedColor:'#746b70',fontFamily:'Tahoma, Arial, sans-serif',buttonRadius:999,cardRadius:20,containerWidth:1180,sectionSpacing:64,globalPadding:18,shadowPreset:'soft'};
  const registry=Object.create(null), categoryGlyphs=['✦','◌','◇','○','✧','◈']; let lastContext=null,countdownTimer=0;
  function registerSection(t,r){registry[t]=r} function asArray(v){return Array.isArray(v)?v:[]} function int(v,f,min,max){const n=Number(v);return Number.isFinite(n)?Math.max(min??-Infinity,Math.min(max??Infinity,Math.floor(n))):f}
  function validDate(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d} function safeExternalUrl(v){if(!v)return'';try{const u=new URL(String(v),location.href);return ['http:','https:','tel:','mailto:'].includes(u.protocol)?u.href:''}catch(e){return''}}
  function safeImageUrl(v){if(!v)return'';if(typeof safeMediaUrl==='function')return safeMediaUrl(v)||'';return safeExternalUrl(v)} function productCategoryName(p){return p&&p.category&&p.category.name?String(p.category.name):'بدون دسته‌بندی'}
  function productAvailability(p){const s=Number(p&&p.stockQty||0),l=Number(p&&p.lowStockAt||0);if(s<=0)return{label:'ناموجود',cls:'is-out'};if(l>0&&s<=l)return{label:'رو به اتمام',cls:'is-low'};return{label:'موجود',cls:'is-in'}}
  function productsByIds(ids,products){const m=new Map(asArray(products).map(p=>[Number(p.id),p]));return asArray(ids).map(Number).map(id=>m.get(id)).filter(Boolean)}
  function firstCategoryProductImage(id,products){const p=asArray(products).find(x=>Number(x.categoryId||(x.category&&x.category.id))===Number(id)&&getProductImageUrl(x));return p?getProductImageUrl(p):''}
  function productCard(p,badge){const image=getProductImageUrl(p),a=productAvailability(p);return '<a class="sf-product-card" href="product-detail.html?id='+encodeURIComponent(p.id)+'"><div class="sf-product-media">'+(image?'<img src="'+escapeHtml(image)+'" alt="'+escapeHtml(p.name)+'" loading="lazy" decoding="async">':'<span class="sf-product-placeholder">✦</span>')+'<span class="sf-stock-badge '+a.cls+'">'+a.label+'</span>'+(badge?'<span class="sf-extra-badge">'+escapeHtml(badge)+'</span>':'')+'</div><div class="sf-product-body"><span class="sf-product-category">'+escapeHtml(productCategoryName(p))+'</span><h3>'+escapeHtml(p.name)+'</h3><div class="sf-product-price">'+escapeHtml(getProductPriceLabel(p))+'</div></div></a>'}
  function sectionHead(t,s,href,link,extra){return '<div class="sf-section-head"><div><h2>'+escapeHtml(t||'')+'</h2>'+(s?'<p>'+escapeHtml(s)+'</p>':'')+'</div>'+(extra||'')+(href?'<a href="'+escapeHtml(href)+'">'+escapeHtml(link||'مشاهده همه')+' <span>‹</span></a>':'')+'</div>'}
  function applyTheme(theme){const t={...DEFAULT_THEME,...(theme||{})},s=document.documentElement.style;s.setProperty('--sf-bg',t.backgroundColor);s.setProperty('--sf-surface',t.surfaceColor);s.setProperty('--sf-ink',t.textColor);s.setProperty('--sf-muted',t.mutedColor);s.setProperty('--sf-rose',t.primaryColor);s.setProperty('--sf-rose-dark',t.primaryColor);s.setProperty('--sf-plum',t.accentColor);s.setProperty('--sf-card-radius',int(t.cardRadius,20,0,80)+'px');s.setProperty('--sf-container',int(t.containerWidth,1180,720,1600)+'px');s.setProperty('--sf-section-space',int(t.sectionSpacing,64,16,160)+'px');s.setProperty('--sf-global-pad',int(t.globalPadding,18,8,64)+'px');document.body.style.fontFamily=t.fontFamily||DEFAULT_THEME.fontFamily}
  function normalizeSections(server){const byType=new Map(asArray(server).map(x=>[x&&x.type,x]));return REQUESTED.map(base=>{const saved=byType.get(base.type)||{};return {...base,...saved,id:base.id,type:base.type,enabled:true,content:{...base.content,...(saved.content||{})},settings:{...base.settings,...(saved.settings||{})}}})}
  registerSection('search',(b,ctx)=>{const chips=['<a class="sf-nav-chip is-primary" href="products.html">همه محصولات</a>'].concat(asArray(ctx.categories).slice(0,8).map(c=>'<a class="sf-nav-chip" href="products.html?category='+encodeURIComponent(c.id)+'">'+escapeHtml(c.name)+'</a>')).join('');return '<section class="sf-search-block sf-container"><form class="sf-search-form" action="products.html" method="get" role="search"><button type="submit" aria-label="جستجو"><span>⌕</span></button><input type="search" name="q" placeholder="دنبال چه محصولی می‌گردی؟" autocomplete="off"></form><div class="sf-chip-strip">'+chips+'</div></section>'});
  registerSection('videos',(b,ctx)=>{const rows=[];asArray(ctx.products).forEach(p=>asArray(p.media).filter(m=>m&&m.kind==='video'&&safeImageUrl(m.url)).forEach(m=>{if(rows.length<int(b.settings&&b.settings.limit,8,1,12))rows.push({product:p,media:m})}));const head=sectionHead((b.content||{}).title||'ویدیوهای آموزشی',(b.content||{}).subtitle||'نکات، آموزش و معرفی محصولات','products.html','مشاهده همه');if(!rows.length)return '<section class="sf-section sf-video-section sf-container">'+head+'<div class="sf-video-demo">'+[1,2,3].map(()=>'<div class="sf-video-demo-card"><span class="sf-play">▶</span></div>').join('')+'</div></section>';return '<section class="sf-section sf-video-section sf-container">'+head+'<div class="sf-video-grid">'+rows.map(r=>'<article class="sf-video-card"><div class="sf-video-media"><video controls muted playsinline preload="metadata"><source src="'+escapeHtml(safeImageUrl(r.media.url))+'"></video></div><div class="sf-video-copy"><span>محتوای آموزشی</span><h3>'+escapeHtml(r.product.name)+'</h3><a href="product-detail.html?id='+encodeURIComponent(r.product.id)+'">محصول مرتبط <b>‹</b></a></div></article>').join('')+'</div></section>'});
  registerSection('best-sellers',(b,ctx)=>{const ids=(b.settings||{}).mode==='manual'?asArray(b.settings.productIds):asArray(ctx.bestSellerIds),picked=productsByIds(ids,ctx.products),products=(picked.length?picked:asArray(ctx.products)).slice(0,int(b.settings&&b.settings.limit,8,1,20));const head=sectionHead((b.content||{}).title||'پرفروش‌ترین‌ها',(b.content||{}).subtitle||'انتخاب‌های محبوب مشتریان','products.html','مشاهده همه');return '<section class="sf-section sf-container sf-best-sellers">'+head+(products.length?'<div class="sf-product-scroll">'+products.map(p=>productCard(p,'پرفروش')).join('')+'</div>':'<div class="sf-section-empty">هنوز محصولی برای نمایش وجود ندارد.</div>')+'</section>'});
  registerSection('campaign',(b,ctx)=>{const chosen=productsByIds((b.settings||{}).productIds,ctx.products);let products=chosen.length?chosen:asArray(ctx.products).filter(p=>Number(p.discountPercent||p.discount||0)>0||Number(p.salePrice||0)>0&&Number(p.price||0)>Number(p.salePrice||0));if(!products.length)products=asArray(ctx.products).slice(0,8);products=products.slice(0,8);const end=validDate(b.settings&&b.settings.endsAt),timer=end?'<div class="sf-countdown" data-end-at="'+escapeHtml(end.toISOString())+'"><span>تا پایان پیشنهاد</span><strong>--:--:--</strong></div>':'';return '<section class="sf-section sf-container sf-campaign-section"><div class="sf-campaign">'+sectionHead((b.content||{}).title||'تخفیف‌ها',(b.content||{}).subtitle||'پیشنهادهای ویژه و محدود','products.html',(b.content||{}).ctaText||'مشاهده همه',timer)+(products.length?'<div class="sf-product-scroll">'+products.map(p=>productCard(p,'تخفیف')).join('')+'</div>':'<div class="sf-section-empty">هنوز محصول تخفیف‌دار ثبت نشده است.</div>')+'</div></section>'});
  registerSection('categories',(b,ctx)=>{const cats=asArray(ctx.categories).slice(0,int(b.settings&&b.settings.limit,8,1,12)),head=sectionHead((b.content||{}).title||'دسته‌بندی محصولات',(b.content||{}).subtitle||'انتخاب سریع‌تر با دسته‌بندی تصویری','products.html','همه دسته‌ها');return '<section class="sf-section sf-container" id="sf-categories">'+head+(cats.length?'<div class="sf-category-grid">'+cats.map((c,i)=>{const image=firstCategoryProductImage(c.id,ctx.products);return '<a class="sf-category-card tone-'+((i%6)+1)+'" href="products.html?category='+encodeURIComponent(c.id)+'"><div class="sf-category-visual">'+(image?'<img src="'+escapeHtml(image)+'" alt="'+escapeHtml(c.name)+'" loading="lazy">':'<span>'+categoryGlyphs[i%categoryGlyphs.length]+'</span>')+'</div><div class="sf-category-copy"><strong>'+escapeHtml(c.name)+'</strong><span>مشاهده ‹</span></div></a>'}).join('')+'</div>':'<div class="sf-section-empty">هنوز دسته‌بندی ثبت نشده است.</div>')+'</section>'});
  function footer(ctx){const s=ctx.store||{},phone=s.phone||s.supportPhone||'',email=s.email||s.supportEmail||'';return '<footer class="sf-footer"><div class="sf-footer-inner sf-container"><div class="sf-footer-brand"><div class="logo">Lumière</div><p>فروشگاه محصولات آرایشی، بهداشتی و مراقبتی</p><div class="sf-footer-contact">'+(phone?'<a href="tel:'+escapeHtml(phone)+'"><span>شماره تماس پشتیبانی</span><b>'+escapeHtml(phone)+'</b></a>':'')+(email?'<a href="mailto:'+escapeHtml(email)+'"><span>ایمیل</span><b>'+escapeHtml(email)+'</b></a>':'')+'</div></div><div class="sf-footer-links"><div><strong>راهنمای خرید</strong><a href="products.html">محصولات</a><a href="cart.html">سبد خرید</a></div><div><strong>حساب کاربری شما</strong><a href="login.html">ورود / ثبت‌نام</a><a href="profile.html">سفارش‌های من</a></div><div><strong>درباره فروشگاه</strong><a href="index.html">صفحه نخست</a><span>پشتیبانی و ارتباط با ما</span></div></div></div><div class="sf-footer-bottom sf-container">Lumière · Beauty · Care</div></footer>'}
  function bindCountdowns(ctx){clearInterval(countdownTimer);function update(){root.querySelectorAll('[data-end-at]').forEach(n=>{const e=validDate(n.dataset.endAt);if(!e)return;let sec=Math.max(0,Math.floor((e.getTime()-(Date.now()+Number(ctx.clockSkewMs||0)))/1000));const h=Math.floor(sec/3600);sec-=h*3600;const m=Math.floor(sec/60),s=sec-m*60,strong=n.querySelector('strong');if(strong)strong.textContent=[h,m,s].map(v=>String(v).padStart(2,'0')).join(':')})}update();countdownTimer=setInterval(update,1000)}
  function renderLayout(sections,ctx){const normalized=normalizeSections(sections),html=normalized.map(b=>{try{return registry[b.type](b,ctx)||''}catch(e){console.error(e);return''}}).join('')+footer(ctx);root.innerHTML=html;bindCountdowns(ctx)}
  function bindMenu(){const t=document.querySelector('.menu-toggle'),c=document.querySelector('.close-menu'),o=document.querySelector('.side-menu-overlay'),m=document.querySelector('.side-menu');if(!m)return;const open=()=>{m.classList.add('open');o&&o.classList.add('open')},close=()=>{m.classList.remove('open');o&&o.classList.remove('open')};t&&t.addEventListener('click',open);c&&c.addEventListener('click',close);o&&o.addEventListener('click',close)}
  function safePromise(p,f){return p.then(v=>v).catch(()=>f)}
  async function bootHome(){bindMenu();try{const r=await Promise.all([safePromise(fetchStoreConfig(),null),safePromise(fetchPublicCategories(),[]),safePromise(apiFetch('/products/public/'+SELLER_ID),[]),safePromise(apiFetch('/storefront/public/'+SELLER_ID+'/home'),null),safePromise(apiFetch('/storefront-insights/public/'+SELLER_ID+'/best-sellers?limit=20'),{productIds:[]})]);const page=r[3],now=page&&page.serverNow?new Date(page.serverNow):new Date(),ctx={store:r[0],categories:r[1]||[],products:r[2]||[],bestSellerIds:r[4]&&r[4].productIds||[],clockSkewMs:now.getTime()-Date.now()};lastContext=ctx;applyTheme(page&&page.theme);renderLayout(page&&page.config&&page.config.sections?page.config.sections:REQUESTED,ctx);if(ctx.store)applyStoreBrand(ctx.store);window.dispatchEvent(new CustomEvent('storefront:home-ready'))}catch(e){console.error(e);root.innerHTML='<section class="sf-load-error sf-container"><strong>خطا در دریافت اطلاعات فروشگاه</strong><p>صفحه را دوباره بارگذاری کنید.</p></section>'}}
  window.addEventListener('message',e=>{if(e.origin!==location.origin||!e.data||e.data.type!=='storefront-preview-config'||!lastContext)return;applyTheme(e.data.theme||DEFAULT_THEME);renderLayout(e.data.config&&e.data.config.sections?e.data.config.sections:REQUESTED,lastContext)});
  window.StorefrontHome={registry,defaultConfig:DEFAULT_CONFIG,defaultTheme:DEFAULT_THEME,registerSection,renderLayout,applyTheme};bootHome();
})();